/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.droste.dirsync.gui;

import com.droste.file.report.Report;
import java.awt.Color;
import java.awt.Font;
import java.util.zip.Adler32;
import java.util.zip.Checksum;

/**
 *
 * @author matthias
 */
public class ReportDialog extends javax.swing.JDialog {

    private Font defaultFont = ((MainFrame)getParent()).getDefaultFont();
    private final boolean simulationMode = ((MainFrame) getParent()).isSimulationMode();;
    private final String verb = (simulationMode) ? "would have been" : "were";
    
    /**
     * Creates new form ReportDialog
     */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        changedFilesTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        newFilesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        newDirectoriesTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        newFilesText = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        summaryText = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        changedFilesText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Synchronization Results");
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.white);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        changedFilesTable.setModel(new SyncTableModel(((MainFrame) getParent()).getReport().getChangedFiles()));
        changedFilesTable.setCellSelectionEnabled(true);
        jScrollPane3.setViewportView(changedFilesTable);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        newFilesTable.setModel(new SyncTableModel(((MainFrame) getParent()).getReport().getNewFiles()));
        newFilesTable.setCellSelectionEnabled(true);
        jScrollPane4.setViewportView(newFilesTable);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        newDirectoriesTable.setModel(new SyncTableModel(((MainFrame)getParent()).getReport().getNewDirectories()));
        newDirectoriesTable.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(newDirectoriesTable);

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);

        newFilesText.setBorder(null);
        newFilesText.setContentType("text/html");
        newFilesText.setText(getNewFilesText());
        jScrollPane5.setViewportView(newFilesText);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane6.setBorder(null);

        jTextPane1.setBorder(null);
        jTextPane1.setContentType("text/html");
        jTextPane1.setText(getNewDirectoriesText());
        jScrollPane6.setViewportView(jTextPane1);

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.setBorder(null);

        summaryText.setBorder(null);
        summaryText.setContentType("text/html");
        summaryText.setText(getSummaryText());
        jScrollPane7.setViewportView(summaryText);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        changedFilesText.setBorder(null);
        changedFilesText.setContentType("text/html");
        changedFilesText.setEditable(false);
        changedFilesText.setText(getChangedFilesText());
        jScrollPane1.setViewportView(changedFilesText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane5)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane7)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String getSummaryText() {
        final MainFrame mainframe = (MainFrame) getParent();
        final Report report = mainframe.getReport();
        int noOfChangedFiles = report.getNoOfChanges();
        double syncTime = report.getSyncTime();
        String simEntry = (simulationMode) ? "Simulation of " : "";
        return "<font face=\"Tahoma 13 Plain, Arial\"><b>"+ simEntry + "Synchronization done in " + syncTime + " seconds. " + noOfChangedFiles + " files and folders " + verb + " copied from the source to the target directory.</b><br/>"
                    + "Overall there were " + report.getNoOfSourceFiles() + " Files and " + report.getNoOfSourceDirectories() + " directories in the source, " + report.getNoOfTargetFiles() + " files in the target."
                    + "<br>Check the information below for the exact list of changes.</font>";
    }
    
    private String getChangedFilesText() {
        int noOfChangedFiles = ((MainFrame) getParent()).getReport().getNoOfChangedFiles();
        return "<font face=\"Tahoma 13 Plain, Arial\"><b>" + noOfChangedFiles + "</b> Files in the source had a different content. They " + verb + " copied to the target with an adapted name.<br>"
                + "Detailed list of changed files:</font>";
    }
    
    private String getNewFilesText() {
        int noOfNewFiles = ((MainFrame) getParent()).getReport().getNoOfNewFiles();
        return "<font face=\"Tahoma 13 Plain, Arial\"><b>" + noOfNewFiles + "</b> new Files were found in the source and " + verb + " copied to the corresponding subdirectories in the target.<br>"
                + "Detailed list of new files:</font>";
    }

    private String getNewDirectoriesText() {
        int noOfNewDirs = ((MainFrame) getParent()).getReport().getNoOfNewDirectories();
        return "<font face=\"Tahoma 13 Plain, Arial\"><b>" + noOfNewDirs + "</b> new Directories " + verb + " created in the target.<br>"
                + "Detailed list of new directories:</font>";
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable changedFilesTable;
    private javax.swing.JTextPane changedFilesText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable newDirectoriesTable;
    private javax.swing.JTable newFilesTable;
    private javax.swing.JTextPane newFilesText;
    private javax.swing.JTextPane summaryText;
    // End of variables declaration//GEN-END:variables

}
