/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.droste.dirsync.gui;

import com.droste.file.report.Report;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author matthias
 */
public class ReportDialog extends javax.swing.JDialog {

    private Font defaultFont = ((MainFrame)getParent()).getDefaultFont();
    /**
     * Creates new form ReportDialog
     */
    public ReportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        changedFilesTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        newFilesTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        newDirectoriesTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        newFilesText = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        summaryText = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        changedFilesText = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Synchronization Results");
        setAlwaysOnTop(true);
        setBackground(java.awt.Color.white);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        changedFilesTable.setModel(new SyncTableModel(((MainFrame) getParent()).getReport().getChangedFiles()));
        jScrollPane3.setViewportView(changedFilesTable);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        newFilesTable.setModel(new SyncTableModel(((MainFrame) getParent()).getReport().getNewFiles()));
        jScrollPane4.setViewportView(newFilesTable);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        newDirectoriesTable.setModel(new SyncTableModel(((MainFrame)getParent()).getReport().getNewDirectories()));
        jScrollPane2.setViewportView(newDirectoriesTable);

        newFilesText.setBorder(null);
        newFilesText.setContentType("text/html");
        newFilesText.setText(getNewFilesText());
        jScrollPane5.setViewportView(newFilesText);

        jTextPane1.setBorder(null);
        jTextPane1.setContentType("text/html");
        jTextPane1.setText(getNewDirectoriesText());
        jScrollPane6.setViewportView(jTextPane1);

        summaryText.setBorder(null);
        summaryText.setContentType("text/html");
        summaryText.setText(getSummaryText());
        jScrollPane7.setViewportView(summaryText);

        changedFilesText.setBorder(null);
        changedFilesText.setContentType("text/html");
        changedFilesText.setEditable(false);
        changedFilesText.setText(getChangedFilesText());
        jScrollPane1.setViewportView(changedFilesText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private String getSummaryText() {
       final Report report = ((MainFrame) getParent()).getReport();
       int noOfChangedFiles = report.getNoOfChanges();
       double syncTime = report.getSyncTime();
        return "<b>Synchronization done in " + syncTime + " seconds. " + noOfChangedFiles + " files and folders were copied from the source to the target directory.</b>"
                + "<br>Check the information below for the exact list of changes.";
    }
    
    private String getChangedFilesText() {
        int noOfChangedFiles = ((MainFrame) getParent()).getReport().getNoOfChangedFiles();
        return "<b>" + noOfChangedFiles + "</b> Files in the source had a different content. They were copied to the target with an adapted name.<br>"
                + "Detailed list of changed files:";
    }
    
    private String getNewFilesText() {
        int noOfNewFiles = ((MainFrame) getParent()).getReport().getNoOfNewFiles();
        return "<b>" + noOfNewFiles + "</b> new Files were found in the source and  copied to the corresponding subdirectories in the target.<br>"
                + "Detailed list of new files:";
    }

    private String getNewDirectoriesText() {
        int noOfNewDirs = ((MainFrame) getParent()).getReport().getNoOfNewDirectories();
        return "<b>" + noOfNewDirs + "</b> new Directories were created in the target.<br>"
                + "Detailed list of new directories:";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ReportDialog dialog = new ReportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable changedFilesTable;
    private javax.swing.JTextPane changedFilesText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable newDirectoriesTable;
    private javax.swing.JTable newFilesTable;
    private javax.swing.JTextPane newFilesText;
    private javax.swing.JTextPane summaryText;
    // End of variables declaration//GEN-END:variables

}
